### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt-contrib-tutor#43]
https://github.com/adaptlearning/adapt-contrib-tutor/blob/develop/js/adapt-contrib-tutor.js#L42

Needs to be moved to the Backbone.View events: {} pattern so that the binding gets properly delegated and undelegated.

**Comment by simondate** [comment]
Link in ticket is 404. I assume this has been fixed?

**Comment by oliverfoster** [comment]
yup
