### ISSUE TITLE
Add class for correct, partially correct and incorrect.

### ISSUE THREAD

**Issue by jscampos** [adaptlearning/adapt-contrib-tutor#56]
Is there a way to add a class to the "notify-popup-content" div or anything above that so I can tell if the feedback is correct, partially correct or incorrect. I want to add special styling depending on the type of feedback being displayed.

**Comment by moloko** [comment]
this was added in v2.0.2 by the looks of [this](https://github.com/adaptlearning/adapt-contrib-tutor/commit/78ab2f50a87683e43122ddc902f42f2bb9fdc675)

**Comment by jscampos** [comment]
Awesome. Thanks!
