### ISSUE TITLE
Partially correct shows incorrect class

### ISSUE THREAD

**Issue by jscampos** [adaptlearning/adapt-contrib-tutor#57]
When the user needs to select more than one option on a mcq and they select only one the mcq component marks it as partially correct but the tutor adds the incorrect class while showing the partially correct content. Is there anyway to get the partially correct class in there?

**Comment by moloko** [comment]
you could maybe do something like check to see if `_isCorrect` is `false` and, if it is, check to see if it the model has a property called `_isAtLeastOneCorrectSelection` and that it's set to `true`?

**Comment by brian-learningpool** [comment]
@jscampos I have a fix for this in #58.
