### ISSUE TITLE
Question component feedback popups opening up on page load

### ISSUE THREAD

**Issue by karthickrk1** [adaptlearning/adapt-contrib-tutor#94]
### Subject of the issue/enhancement/features
Question component with tutor extension, feedback popups open automatically if you leave the page that contains a completed question and navigate back to it. 

### Your environment
* adapt-framwork - v5.31.6
* Browser - Chrome, Edge
* OS - Windows
* Extension - adapt-contrib-tutor v4.5.7

### Steps to reproduce
Answer the question and navigate to other page and come back to same question page.. The feedback popup is shown.

### Expected behaviour
If you leave the page that contains a completed question and navigate back to it (this includes going to the menu and then going back to the page), It should not open the feedback popups

### Actual behaviour
Question component feedback popups open automatically if you leave the page that contains a completed question and navigate back to it.

### Screenshots (if you can)
![adapt-contrib-tutor_v4 5 7](https://github.com/adaptlearning/adapt_framework/assets/132436261/203c055c-635e-4812-8778-03008040241c)

**Comment by swashbuck** [comment]
Related to https://github.com/adaptlearning/adapt_framework/issues/3418

**Comment by fosterc1** [comment]
This definitely issue appears to be an issue introduce in v4.5.6 of the plugin.

I can replicate the issue with the following:

- FW v5.31.9 / Tutor v4.5.7
- FW v5.31.9 / Tutor v4.5.6
- FW v5.31.2 /Tutor v4.5.7

This is however working with
FW v5.31.2 / Tutor v4.5.5
FW v5.31.3 / Tutor v4.5.5
FW v5.31.4 / Tutor v4.5.5
FW v5.31.5 / Tutor v4.5.5
FW v5.31.6 / Tutor v4.5.5
FW v5.31.7 / Tutor v4.5.5
FW v5.31.8 / Tutor v4.5.5
FW v5.31.9 / Tutor v4.5.5

Hope this helps

**Comment by oliverfoster** [comment]
Should be fixed with pr #101
